### ISSUE TITLE
[Docs]: Ports and Firewall

### ISSUE THREAD

**Issue by felipeavilis** [openlit/openlit#573]
The `docker-compose.yaml` file exposes several ports, but I couldn't find in the documentation which ports are made for what. My microservices runs in other servers and I'm gonna have to put OpenLIT behind a Nginx Proxy. 

Please, correct me if im wrong. What i could find is:

| Service | Port | Description | External Use |
|---|---|---|---|
| openlit | 3000   | Used to access UI via Web Browser | Yes |
| otel-collector |  4317 | GRPC server | No |
| otel-collector | 4318 | HTTP server | Yes |
| otel-collector |  8888 | Metrics | Optional |
| otel-collector |  55679 | zPages | No |
| clickhouse |  8123 | DB for Opentelemetry Collector | No |
| clickhouse |  9000 | DB for OpenLIT | No |

I'm trying to secure services in docker creating an internal network, but i need to know wich ports must be exposed to host, and wich ports dont. 

Here is my `docker-compose.yaml` file.
```yaml
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.4.1
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      CLICKHOUSE_USER: ${OPENLIT_DB_USER:-default}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    #ports:
      #- "9000:9000"
      #- "8123:8123"
    restart: unless-stopped
    networks:
      - openlit

  openlit:
    image: ghcr.io/openlit/openlit:latest
    container_name: openlit
    environment:
      TELEMETRY_ENABLED: true
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 8123
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    volumes:
      - openlit-data:/app/client/data
    restart: unless-stopped
    networks:
      - openlit

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 9000
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
    ports:
      #- "4317:4317"
      - "4318:4318"
      - "8888:8888"
      #- "55679:55679"
    depends_on:
      - clickhouse
    volumes:
      - ./assets/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    restart: unless-stopped
    networks:
      - openlit

volumes:
  clickhouse-data:
  openlit-data:

networks:
  openlit:
    driver: bridge
```

Can you help me with this?
